# spring.application.nam e=mohit

spring.data.mongodb.uri=mongodb+srv://mohit:Mohitsoni123@developer-mohit.vgkkf.mongodb.net/?retryWrites=true&w=majority&appName=developer-mohit
spring.data.mongodb.database=developer-mohit
spring.data.mongodb.auto-index-creation=true

# spring :
#     data :
#         mongodb :
#             uri: mongodb+srv://mohit:Mohitsoni123@developer-mohit.vgkkf.mongodb.net/?retryWrites=true&w=majority&appName=developer-mohit 
#             database : developer-mohit
#             auto-index-creation : true
