# spring.application.nam e=mohit
spring.config.import=optional:file:.env

spring.data.mongodb.uri=${DATASOURCE_URL}
spring.data.mongodb.database=${DATASOURCE_DATABASE}
spring.data.mongodb.auto-index-creation=true

server.port:8080
